structure(list(method = "GET", url = "https://opendata.fmi.fi/meta?observableProperty=observation&param=WD_PT1H_AVG,WS_PT1H_AVG,WS_PT1H_MAX,WS_PT1H_MIN&language=eng", 
    status_code = 200L, headers = structure(list(`Access-Control-Allow-Origin` = "*", 
        `Cache-Control` = "public, max-age=60", `Content-Encoding` = "gzip", 
        `Content-Length` = "512", `Content-Type` = "text/xml; charset=UTF-8", 
        Date = "Tue, 16 Jul 2024 05:49:38 GMT", Expires = "Tue, 16 Jul 2024 05:50:38 GMT", 
        `Last-Modified` = "Tue, 16 Jul 2024 05:49:38 GMT", Server = "SmartMet Server (12:10:04 May 16 2024)", 
        Vary = "Accept-Encoding", Connection = "Keep-Alive"), class = "httr2_headers"), 
    body = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<CompositeObservableProperty xmlns=\"http://inspire.ec.europa.eu/schemas/omop/2.9\"\n  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n  xmlns:gml=\"http://www.opengis.net/gml/3.2\"\n  xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n  gml:id=\"prop-1\"\n  xsi:schemaLocation=\"http://inspire.ec.europa.eu/schemas/omop/2.9 http://inspire.ec.europa.eu/draft-schemas/omop/2.9/ObservableProperties.xsd\">\n  <count>4</count>\n    <component>\n      <ObservableProperty gml:id=\"wd_pt1h_avg\">\n        <label>Wind direction</label>\n      \t<basePhenomenon>Wind</basePhenomenon>\n      \t<uom uom=\"deg\"/>\n      \t<statisticalMeasure>     \n          <StatisticalMeasure gml:id=\"stat-avg-PT1H-wd_pt1h_avg---\">\n            <statisticalFunction>avg</statisticalFunction><aggregationTimePeriod>PT1H</aggregationTimePeriod>\n          </StatisticalMeasure>\n        </statisticalMeasure>\n      </ObservableProperty>\n    </component>  \n    <component>\n      <ObservableProperty gml:id=\"ws_pt1h_avg\">\n        <label>Wind speed</label>\n      \t<basePhenomenon>Wind</basePhenomenon>\n      \t<uom uom=\"m/s\"/>\n      \t<statisticalMeasure>     \n          <StatisticalMeasure gml:id=\"stat-avg-PT1H-ws_pt1h_avg---\">\n            <statisticalFunction>avg</statisticalFunction><aggregationTimePeriod>PT1H</aggregationTimePeriod>\n          </StatisticalMeasure>\n        </statisticalMeasure>\n      </ObservableProperty>\n    </component>  \n    <component>\n      <ObservableProperty gml:id=\"ws_pt1h_max\">\n        <label>Maximum wind speed</label>\n      \t<basePhenomenon>Wind</basePhenomenon>\n      \t<uom uom=\"m/s\"/>\n      \t<statisticalMeasure>     \n          <StatisticalMeasure gml:id=\"stat-max-PT1H-ws_pt1h_max---\">\n            <statisticalFunction>max</statisticalFunction><aggregationTimePeriod>PT1H</aggregationTimePeriod>\n          </StatisticalMeasure>\n        </statisticalMeasure>\n      </ObservableProperty>\n    </component>  \n    <component>\n      <ObservableProperty gml:id=\"ws_pt1h_min\">\n        <label>Minimum wind speed</label>\n      \t<basePhenomenon>Wind</basePhenomenon>\n      \t<uom uom=\"m/s\"/>\n      \t<statisticalMeasure>     \n          <StatisticalMeasure gml:id=\"stat-min-PT1H-ws_pt1h_min---\">\n            <statisticalFunction>min</statisticalFunction><aggregationTimePeriod>PT1H</aggregationTimePeriod>\n          </StatisticalMeasure>\n        </statisticalMeasure>\n      </ObservableProperty>\n    </component>  </CompositeObservableProperty>\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
