structure(list(url = "https://opendata.fmi.fi/meta?observableProperty=observation&param=TG_PT12H_min&language=eng", 
    status_code = 200L, headers = structure(list(`access-control-allow-origin` = "*", 
        `cache-control` = "public, max-age=60", `content-length` = "855", 
        `content-type` = "text/xml; charset=UTF-8", date = "Thu, 11 Jul 2024 08:28:50 GMT", 
        expires = "Thu, 11 Jul 2024 08:29:50 GMT", `last-modified` = "Thu, 11 Jul 2024 08:28:50 GMT", 
        server = "SmartMet Server (12:10:04 May 16 2024)", vary = "Accept-Encoding", 
        connection = "Keep-Alive"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.0", 
        headers = structure(list(`access-control-allow-origin` = "*", 
            `cache-control` = "public, max-age=60", `content-length` = "855", 
            `content-type` = "text/xml; charset=UTF-8", date = "Thu, 11 Jul 2024 08:28:50 GMT", 
            expires = "Thu, 11 Jul 2024 08:29:50 GMT", `last-modified` = "Thu, 11 Jul 2024 08:28:50 GMT", 
            server = "SmartMet Server (12:10:04 May 16 2024)", 
            vary = "Accept-Encoding", connection = "Keep-Alive"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n<ObservableProperty xmlns=\"http://inspire.ec.europa.eu/schemas/omop/2.9\"\n  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n  xmlns:gml=\"http://www.opengis.net/gml/3.2\"\n  xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n  gml:id=\"tg_pt12h_min\"\n  xsi:schemaLocation=\"http://inspire.ec.europa.eu/schemas/omop/2.9 http://inspire.ec.europa.eu/draft-schemas/omop/2.9/ObservableProperties.xsd\">\n        <label>Ground minimum temperature</label>\n      \t<basePhenomenon>Temperature</basePhenomenon>\n      \t<uom uom=\"degC\"/>\n      \t<statisticalMeasure>     \n          <StatisticalMeasure gml:id=\"stat-min-PT12H-tg_pt12h_min---\">\n            <statisticalFunction>min</statisticalFunction><aggregationTimePeriod>PT12H</aggregationTimePeriod>\n          </StatisticalMeasure>\n        </statisticalMeasure>  </ObservableProperty>\n"), 
    date = structure(1720686530, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.01193, 
    connect = 0.018509, pretransfer = 0.047879, starttransfer = 0.061524, 
    total = 0.061529)), class = "response")
