structure(list(method = "GET", url = "http://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi%3A%3Aobservations%3A%3Aweather%3A%3Amonthly%3A%3Asimple&starttime=2019-01-01&endtime=2019-01-02&fmisid=100946", 
    status_code = 200L, headers = structure(list(`Access-Control-Allow-Origin` = "*", 
        `Cache-Control` = "public, max-age=600", `Content-Encoding` = "gzip", 
        `Content-Length` = "513", `Content-Type` = "text/xml; charset=UTF-8", 
        Date = "Mon, 15 Jul 2024 12:47:36 GMT", Expires = "Mon, 15 Jul 2024 12:57:36 GMT", 
        `Last-Modified` = "Mon, 15 Jul 2024 12:47:36 GMT", Server = "SmartMet Server (12:10:04 May 16 2024)", 
        Vary = "Accept-Encoding", Connection = "Keep-Alive"), class = "httr2_headers"), 
    body = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<wfs:FeatureCollection\n  timeStamp=\"2024-07-15T12:47:36Z\"\n  numberReturned=\"2\"\n  numberMatched=\"2\"\n      xmlns:wfs=\"http://www.opengis.net/wfs/2.0\"\n    xmlns:gml=\"http://www.opengis.net/gml/3.2\"\n    xmlns:BsWfs=\"http://xml.fmi.fi/schema/wfs/2.0\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n    xsi:schemaLocation=\"http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd\n                        http://xml.fmi.fi/schema/wfs/2.0 https://xml.fmi.fi/schema/wfs/2.0/fmi_wfs_simplefeature.xsd\"\n>\n  \t\n\t<wfs:member>\n            <BsWfs:BsWfsElement gml:id=\"BsWfsElement.1.1.1\">\n                <BsWfs:Location>\n                    <gml:Point gml:id=\"BsWfsElementP.1.1.1\" srsDimension=\"2\" srsName=\"http://www.opengis.net/def/crs/EPSG/0/4258\">\n                        <gml:pos>59.80864 22.91246 </gml:pos>\n                    </gml:Point>\n                </BsWfs:Location>\n                <BsWfs:Time>2019-01-01T00:00:00Z</BsWfs:Time>\n                <BsWfs:ParameterName>rrmon</BsWfs:ParameterName>\n                <BsWfs:ParameterValue>NaN</BsWfs:ParameterValue>\n            </BsWfs:BsWfsElement>\n\t</wfs:member>\n\t\n\t<wfs:member>\n            <BsWfs:BsWfsElement gml:id=\"BsWfsElement.1.1.2\">\n                <BsWfs:Location>\n                    <gml:Point gml:id=\"BsWfsElementP.1.1.2\" srsDimension=\"2\" srsName=\"http://www.opengis.net/def/crs/EPSG/0/4258\">\n                        <gml:pos>59.80864 22.91246 </gml:pos>\n                    </gml:Point>\n                </BsWfs:Location>\n                <BsWfs:Time>2019-01-01T00:00:00Z</BsWfs:Time>\n                <BsWfs:ParameterName>tmon</BsWfs:ParameterName>\n                <BsWfs:ParameterValue>-2.1</BsWfs:ParameterValue>\n            </BsWfs:BsWfsElement>\n\t</wfs:member>\n\t\n\n</wfs:FeatureCollection>\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
